version: '3.6'
### get network
### ifconfig -l | xargs -n1 ipconfig getifaddr
networks:
  app-tier:
    driver: bridge
    
services: 
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
          - "3306"
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ueo
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
          - "3306:3306"    
        networks:
          - app-tier      
    
        volumes: 
            - ./init:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080